const test = require('brittle')
const path = require('path')
const fs = require('fs')
const tmp = require('test-tmp')

const Hyperschema = require('hyperschema')
const HyperschemaTS = require('../index.cjs')

function buildSchema() {
  const schema = Hyperschema.from(null)
  const ns = schema.namespace('example')

  ns.register({
    name: 'sub',
    fields: [
      { name: 'x', type: 'uint' },
      { name: 'flag', type: 'bool', required: true }
    ]
  })

  ns.register({ name: 'color', enum: ['red', 'green', 'blue'], strings: true })
  ns.register({ name: 'level', enum: ['low', 'high'] })
  ns.register({ name: 'colorAlias', alias: 'string' })
  ns.register({ name: 'tags', array: true, type: 'string' })
  ns.register({ name: 'counts', record: true, key: 'string', value: 'uint' })

  ns.register({
    name: 'request',
    fields: [
      { name: 'id', type: 'uint', required: true },
      { name: 'name', type: 'string', required: true },
      { name: 'score', type: 'float64' },
      { name: 'big', type: 'bigint' },
      { name: 'blob', type: 'buffer' },
      { name: 'created', type: 'date' },
      { name: 'host', type: 'ipv4' },
      { name: 'labels', type: 'string', array: true },
      { name: 'meta', type: '@example/sub' },
      { name: 'colour', type: '@example/color' },
      { name: 'lookup', type: '@example/counts' }
    ]
  })

  return schema
}

test('struct interface with required and optional fields', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('export interface ExampleRequest {'))
  t.ok(out.includes('id: number'), 'required scalar is not optional')
  t.ok(out.includes('name: string'))
})

test('optional object/string/buffer fields are nullable on decode', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('blob?: Buffer | null'))
  t.ok(out.includes('created?: Date | null'))
  t.ok(out.includes('meta?: ExampleSub | null'))
  t.ok(out.includes('labels?: string[] | null'), 'optional array defaults to null')
})

test('optional scalar fields with a default are not nullable', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('score?: number'))
  t.ok(out.includes('big?: bigint'))
  t.absent(out.includes('score?: number | null'))
})

test('bool is always optional (auto-downgraded by hyperschema)', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('flag?: boolean'))
})

test('string enum becomes a string-literal union', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('export type ExampleColor = "red" | "green" | "blue"'))
})

test('numeric enum becomes a numeric-literal union', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('export type ExampleLevel = 1 | 2'))
})

test('alias, array and record top-level types', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('export type ExampleColorAlias = string'))
  t.ok(out.includes('export type ExampleTags = string[]'))
  t.ok(out.includes('export type ExampleCounts = Record<string, number>'))
})

test('references resolve to generated type names', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('colour?: ExampleColor | null'))
  t.ok(out.includes('lookup?: ExampleCounts | null'))
})

test('header records the schema version', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('autogenerated by hyperschema-ts'))
  t.ok(out.includes('Schema version: 1'))
})

test('typeName helper', (t) => {
  t.is(HyperschemaTS.typeName('@example/my-struct'), 'ExampleMyStruct')
  t.is(HyperschemaTS.typeName('plain'), 'Plain')
})

test('toDisk writes types.d.ts to the schema dir', async (t) => {
  const dir = await tmp(t)
  const out = HyperschemaTS.toDisk(buildSchema(), dir)

  t.is(out, path.join(path.resolve(dir), 'types.d.ts'))
  t.ok(fs.existsSync(out))
  t.ok(fs.readFileSync(out, 'utf-8').includes('export interface ExampleRequest {'))
})

test('toDisk respects opts.filename', async (t) => {
  const dir = await tmp(t)
  const filename = path.join(dir, 'custom.d.ts')
  const out = HyperschemaTS.toDisk(buildSchema(), { filename })

  t.is(out, filename)
  t.ok(fs.existsSync(filename))
})

test('emits a SchemaTypes registry mapping fqn -> type', (t) => {
  const out = HyperschemaTS.toCode(buildSchema())

  t.ok(out.includes('export interface SchemaTypes {'))
  t.ok(out.includes(`"@example/request": ExampleRequest`))
  t.ok(out.includes(`"@example/color": ExampleColor`))
  t.ok(out.includes(`"@example/counts": ExampleCounts`))
})

test('registry can be disabled', (t) => {
  const out = HyperschemaTS.toCode(buildSchema(), { registry: false })

  t.absent(out.includes('SchemaTypes'))
})

test('json defaults to unknown', (t) => {
  const schema = Hyperschema.from(null)
  const ns = schema.namespace('example')
  ns.register({ name: 'blob', fields: [{ name: 'payload', type: 'json' }] })

  t.ok(HyperschemaTS.toCode(schema).includes('payload?: unknown'))
})

test('tsType annotation overrides the field type', (t) => {
  const schema = Hyperschema.from(null)
  const ns = schema.namespace('example')
  ns.register({
    name: 'doc',
    fields: [
      { name: 'metrics', type: 'json', tsType: 'Metrics', required: true },
      { name: 'ids', type: 'string', array: true, tsType: 'Id' },
      { name: 'status', type: 'string', tsType: '"on" | "off"' }
    ]
  })

  const out = HyperschemaTS.toCode(schema)
  t.ok(out.includes('metrics: Metrics'), 'json field branded')
  t.ok(out.includes('ids?: Id[]'), 'array override wraps element type')
  t.ok(out.includes(`status?: "on" | "off" | null`), 'union override + nullable')
})
