// Generates TypeScript type declarations from a resolved Hyperschema instance.
// Pure: reads the already-resolved `hyperschema.types` graph, returns a string.

// Maps every compact-encoding primitive (see hyperschema's lib/types.js) to a TS type.
const PRIMITIVE_GROUPS = {
  number: [
    'uint',
    'uint1',
    'uint2',
    'uint3',
    'uint4',
    'uint5',
    'uint6',
    'uint7',
    'uint8',
    'uint16',
    'uint24',
    'uint32',
    'uint40',
    'uint48',
    'uint56',
    'uint64',
    'int',
    'int8',
    'int16',
    'int24',
    'int32',
    'int40',
    'int48',
    'int56',
    'int64',
    'float32',
    'float64',
    'port',
    'lexint'
  ],
  string: ['string', 'utf8', 'ascii', 'hex', 'ip', 'ipv4', 'ipv6'],
  bigint: ['bigint', 'biguint64', 'bigint64'],
  Buffer: ['fixed32', 'fixed64', 'buffer', 'optionalBuffer', 'raw'],
  boolean: ['bool'],
  Date: ['date'],
  null: ['none'],
  unknown: ['json']
}

// Primitives whose encoded value is an object rather than a scalar.
const PRIMITIVE_OBJECTS = {
  ipAddress: '{ host: string; family?: number; port: number }',
  ipv4Address: '{ host: string; family?: number; port: number }',
  ipv6Address: '{ host: string; family?: number; port: number }'
}

const PRIMITIVES = new Map()
for (const [ts, names] of Object.entries(PRIMITIVE_GROUPS)) {
  for (const name of names) PRIMITIVES.set(name, ts)
}
for (const [name, ts] of Object.entries(PRIMITIVE_OBJECTS)) PRIMITIVES.set(name, ts)

function pascal(segment) {
  return segment
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('')
}

function typeName(fqn) {
  const stripped = fqn[0] === '@' ? fqn.slice(1) : fqn
  return stripped.split('/').map(pascal).join('')
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/
function fieldKey(name) {
  return IDENT.test(name) ? name : JSON.stringify(name)
}

// Resolve a ResolvedType (+ array flag) to its TS expression.
function tsType(type, array, externals) {
  if (array) return wrap(tsType(type, false, externals)) + '[]'
  if (type.isPrimitive) return PRIMITIVES.get(type.name) || 'unknown'
  if (type.isExternal) return externals[type.fqn] || 'unknown'
  return typeName(type.fqn)
}

// A field's TS type, honouring a per-field `tsType` annotation (like Drizzle's
// `.$type<T>()`) which overrides the resolved element type without affecting encoding.
function fieldTsType(field, externals) {
  const override = field.description && field.description.tsType
  if (!override) return tsType(field.type, field.array, externals)
  return field.array ? wrap(override) + '[]' : override
}

function wrap(t) {
  // parenthesise unions before appending `[]`
  return /[|&]/.test(t) ? `(${t})` : t
}

function structToInterface(type, externals) {
  const lines = [`export interface ${typeName(type.fqn)} {`]
  for (const field of type.fields) {
    const ts = fieldTsType(field, externals)
    const def = field.getDefaultValue() // undefined (useDefault:false) | null | scalar
    if (field.required) {
      lines.push(`  ${fieldKey(field.name)}: ${ts}`)
    } else {
      const nullable = def === null // object/string/buffer/array optionals decode to null
      lines.push(`  ${fieldKey(field.name)}?: ${ts}${nullable ? ' | null' : ''}`)
    }
  }
  lines.push('}')
  return lines.join('\n')
}

function enumToType(type) {
  if (!type.enum.length) return `export type ${typeName(type.fqn)} = never`
  const members = type.strings
    ? type.enum.map((e) => JSON.stringify(e.key))
    : type.enum.map((_, i) => String(type.offset + i))
  return `export type ${typeName(type.fqn)} = ${members.join(' | ')}`
}

// fqn -> generated type name, for every type that produces a top-level declaration.
function registryToInterface(registry) {
  const lines = ['export interface SchemaTypes {']
  for (const [fqn, name] of registry) lines.push(`  ${JSON.stringify(fqn)}: ${name}`)
  lines.push('}')
  return lines.join('\n')
}

function emit(hyperschema, { externals = {}, registry = true } = {}) {
  const decls = []
  const entries = []

  for (const type of hyperschema.types.values()) {
    if (type.derived) continue

    if (type.isStruct) {
      decls.push(structToInterface(type, externals))
    } else if (type.isEnum) {
      decls.push(enumToType(type))
    } else if (type.isAlias) {
      decls.push(`export type ${typeName(type.fqn)} = ${tsType(type.type, false, externals)}`)
    } else if (type.isArray) {
      decls.push(
        `export type ${typeName(type.fqn)} = ${wrap(tsType(type.type, false, externals))}[]`
      )
    } else if (type.isRecord) {
      decls.push(
        `export type ${typeName(type.fqn)} = Record<string, ${tsType(type.value, false, externals)}>`
      )
    } else {
      // primitives / externals / versioned: nothing top-level
      continue
    }
    entries.push([type.fqn, typeName(type.fqn)])
  }

  if (registry) decls.push(registryToInterface(entries))

  const header = [
    '// This file is autogenerated by hyperschema-ts',
    `// Schema version: ${hyperschema.version}`,
    '// Do not edit manually.',
    '',
    ''
  ].join('\n')

  return header + decls.join('\n\n') + '\n'
}

module.exports = { emit, typeName }
